# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

$LOAD_PATH.unshift File.expand_path 'lib', __dir__

%w[vagrant-env].each do |plugin|
  next if Vagrant.has_plugin? plugin

  puts "#{plugin} is not installed!"
  puts 'To install the plugin, run:'
  puts "vagrant plugin install #{plugin}"
  exit
end

Vagrant.configure('2') do |config|
  config.env.load './.env'

  config.vm.box_check_update = false
  config.vm.box = ENV.fetch('VAGRANT_VM_BOX', 'gusztavvargadr/windows-10').to_s
  config.vm.box_version = ENV.fetch('VAGRANT_VM_BOX_VERSION', '2202.0.2211').to_s
  config.vm.hostname = ENV.fetch('VAGRANT_VM_HOSTNAME', 'windows').to_s

  ip_addr = IPAddr.new(ENV['VAGRANT_VM_NETWORK_SUBNET']).succ.to_s
  config.vm.network :private_network, ip: IPAddr.new(ip_addr).succ.to_s

  config.vm.synced_folder './', '/vagrant', owner: 'vagrant', group: 'vagrant'

  config.vm.provider :virtualbox do |vb|
    vb.name = 'windows_10'
    vb.memory = 4096
    vb.cpus = 2
    vb.customize [
      'guestproperty', 'set', :id,
      '/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold', 20_000
    ]
    vb.customize ['modifyvm', :id, '--ioapic', 'on']
    vb.customize ['modifyvm', :id, '--vram', '4']
  end
end
