# frozen_string_literal: true

# -*- mode: ruby -*-
# vi: set ft=ruby :

$LOAD_PATH.unshift File.expand_path 'lib', __dir__

require 'os'

%w[vagrant-env vagrant-timezone].each do |plugin|
  next if Vagrant.has_plugin? plugin

  puts "#{plugin} is not installed!"
  puts 'To install the plugin, run:'
  puts "vagrant plugin install #{plugin}"
  exit
end

Vagrant.configure('2') do |config|
  config.env.load './.env'

  config.vm.box_check_update = false
  config.vm.box = ENV.fetch('VAGRANT_VM_BOX', 'centos/7').to_s
  config.vm.hostname = ENV.fetch('VAGRANT_VM_HOSTNAME', 'centos').to_s

  ip_addr = IPAddr.new(ENV['VAGRANT_VM_NETWORK_SUBNET']).succ.to_s
  config.vm.network :private_network, ip: IPAddr.new(ip_addr).succ.to_s

  if OS.unix?
    config.vm.synced_folder './', '/vagrant', type: 'nfs'
  else
    config.vm.synced_folder './', '/vagrant', owner: 'vagrant', group: 'vagrant'
  end

  config.timezone.value = 'America/Sao_Paulo'

  config.vm.provider :virtualbox do |vb|
    vb.name = 'centos_7'
    vb.memory = 4096
    vb.cpus = 2
    vb.customize [
      'guestproperty', 'set', :id,
      '/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold', 20_000
    ]
    vb.customize ['setextradata', :id, 'VBoxInternal/CPUM/IsaExts/AVX', '1']
    vb.customize ['setextradata', :id, 'VBoxInternal/CPUM/IsaExts/AVX2', '1']
    vb.customize ['modifyvm', :id, '--ioapic', 'on']
    vb.customize ['modifyvm', :id, '--vram', '4']
  end
end
